server:
  port: 8080

spring:
  application:
    name: wx-gout-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.24.88.212:3306/wx_gout_manager?useSSL=true&userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Long050720
  data:
    redis:
      host: 120.24.88.212
      port: 6379
      password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml

aliyun:
  smsCode:
    access-key-id: LTAl5t7Kk8CipDQdjZUHY2AB8
    access-key-secret: IWMv72NfQ1nGSDFHu14uW51rwwysM
    region-id: cn-hangzhou
    template-code: SMS_296735552